# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.3.4

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="An XMPP client library"
HOMEPAGE="https://github.com/pontarius/pontarius-xmpp/"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="+with-th"

RDEPEND=">=dev-haskell/attoparsec-0.10.0.3:=[profile?]
	>=dev-haskell/base64-bytestring-0.1.0.0:=[profile?]
	>=dev-haskell/binary-0.4.1:=[profile?]
	>=dev-haskell/conduit-1.0.1:=[profile?]
	>=dev-haskell/crypto-api-0.9:=[profile?]
	>=dev-haskell/crypto-random-0.0.5:=[profile?]
	>=dev-haskell/cryptohash-0.6.1:=[profile?]
	>=dev-haskell/cryptohash-cryptoapi-0.1:=[profile?]
	>=dev-haskell/data-default-0.2:=[profile?]
	>=dev-haskell/dns-0.3.0:=[profile?]
	>=dev-haskell/hslogger-1.1.0:=[profile?]
	>=dev-haskell/iproute-1.2.4:=[profile?]
	>=dev-haskell/lifted-base-0.1.0.1:=[profile?]
	>=dev-haskell/mtl-2.0.0.0:=[profile?]
	>=dev-haskell/network-2.3.1.0:=[profile?]
	>=dev-haskell/puremd5-2.1.2.1:=[profile?]
	>=dev-haskell/random-1.0.0.0:=[profile?]
	>=dev-haskell/resourcet-0.3.0:=[profile?]
	>=dev-haskell/split-0.1.2.3:=[profile?]
	>=dev-haskell/stm-2.1.2.1:=[profile?]
	>=dev-haskell/stringprep-0.1.3:=[profile?]
	>=dev-haskell/text-0.11.1.5:=[profile?]
	>=dev-haskell/tls-1.1.3:=[profile?]
	>=dev-haskell/tls-extra-0.6.0:=[profile?]
	>=dev-haskell/transformers-0.2.2.0:=[profile?]
	>=dev-haskell/void-0.5.5:=[profile?]
	>=dev-haskell/xml-conduit-1.1.0.7:=[profile?]
	>=dev-haskell/xml-picklers-0.3.3:=[profile?]
	>=dev-haskell/xml-types-0.3.1:=[profile?]
	>=dev-lang/ghc-7.0.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.10.0.0
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag with-th with-th)
}
